/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 models\Deer.gltf --output output\Deer.js --transform --keepnames --shadows 
Files: models\Deer.gltf [3.29MB] > F:\My Documents\Articles Media\AMCOT\Models\Quaternius\Animals\JSX\output\Deer-transformed.glb [517KB] (84%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Quaternius/Animals/Models/Deer.glb`

export function ModelQuaterniusAnimalsDeer(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(link)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
  
      console.log("Actions deer", actions)

      if (props.action) {
        actions[props.action].play();
      }
  
  }, [actions]);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
        </group>
        <group name="Deer">
          <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube.skeleton} />
          <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_1.skeleton} />
          <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_2.skeleton} />
          <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_3.skeleton} />
          <skinnedMesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_4.skeleton} />
          <skinnedMesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_5.skeleton} />
          <skinnedMesh name="Cube_6" geometry={nodes.Cube_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)
