/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\models\Grass Platform.glb --output output\Grass Platform.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/J-Toastie/Models/Grass Platform.glb`;

export function ModelJToastieGrassPlatform(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh name="GrassPlatform_Cylinder001-Mesh" castShadow receiveShadow geometry={nodes['GrassPlatform_Cylinder001-Mesh'].geometry} material={materials.Dirt} />
      <mesh name="GrassPlatform_Cylinder001-Mesh_1" castShadow receiveShadow geometry={nodes['GrassPlatform_Cylinder001-Mesh_1'].geometry} material={materials.Grass} />
    </group>
  )
}

useGLTF.preload(link)
