/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 catching-game-custom-acorn.glb -T 
Files: catching-game-custom-acorn.glb [846.51KB] > F:\My Documents\Sites\games\catching-game\public\models\catching-game-custom-acorn-transformed.glb [48.27KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelAcornMascot(props) {
  const { nodes, materials } = useGLTF('/models/ModelAcornMascot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.acorn.geometry} material={materials.None} position={[-0.023, 0, 0]} rotation={[0.401, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.PaletteMaterial001} position={[-0.123, -0.334, 0.418]} scale={0.065} />
      <mesh geometry={nodes.nose3_toonyMouths_1001.geometry} material={materials.PaletteMaterial002} position={[-0.002, -0.542, 0.465]} rotation={[0.194, 0, 0]} scale={[0.023, 0.015, 0.015]} />
    </group>
  )
}

useGLTF.preload('/models/ModelAcornMascot-transformed.glb')
