/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\rock_tallE.glb --output output\rock_tallE.js --transform 
Files: models\rock_tallE.glb [5.19KB] > E:\Downloads\kenney_nature-kit\JSX\output\rock_tallE-transformed.glb [2.76KB] (47%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/Nature/Models/rock_tallE-transformed.glb`;

export function ModelKennyNLNatureRockTallE(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.05, 0]}>
        <mesh geometry={nodes.Mesh_rock_tallE.geometry} material={materials.dirt} />
        <mesh geometry={nodes.Mesh_rock_tallE_1.geometry} material={materials.grass} />
        <mesh geometry={nodes.Mesh_rock_tallE_2.geometry} material={materials._defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload(link)
